export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL'

export const COURSE_QANDA_REQUEST = 'COURSE_QANDA_REQUEST'
export const COURSE_QANDA_SUCCESS = 'COURSE_QANDA_SUCCESS'
export const COURSE_QANDA_FAIL = 'COURSE_QANDA_FAIL'
export const COURSE_QANDA_RESET = 'COURSE_QANDA_RESET'

export const COURSE_BEST_REQUEST = 'COURSE_BEST_REQUEST'
export const COURSE_BEST_SUCCESS = 'COURSE_BEST_SUCCESS'
export const COURSE_BEST_FAIL = 'COURSE_BEST_FAIL'
