export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'

export const COURSE_CATEGORIES_REQUEST = 'COURSE_CATEGORIES_REQUEST'
export const COURSE_CATEGORIES_SUCCESS = 'COURSE_CATEGORIES_SUCCESS'
export const COURSE_CATEGORIES_FAIL = 'COURSE_CATEGORIES_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL'
<<<<<<< HEAD
export const COURSE_DETAILS_RESET = 'COURSE_DETAILS_RESET'
=======
>>>>>>> f4a828b (initial)

export const COURSE_QANDA_REQUEST = 'COURSE_QANDA_REQUEST'
export const COURSE_QANDA_SUCCESS = 'COURSE_QANDA_SUCCESS'
export const COURSE_QANDA_FAIL = 'COURSE_QANDA_FAIL'
export const COURSE_QANDA_RESET = 'COURSE_QANDA_RESET'

<<<<<<< HEAD
export const COURSE_ANSWER_QANDA_REQUEST = 'COURSE_ANSWER_QANDA_REQUEST'
export const COURSE_ANSWER_QANDA_SUCCESS = 'COURSE_ANSWER_QANDA_SUCCESS'
export const COURSE_ANSWER_QANDA_FAIL = 'COURSE_ANSWER_QANDA_FAIL'
export const COURSE_ANSWER_QANDA_RESET = 'COURSE_ANSWER_QANDA_RESET'

=======
>>>>>>> f4a828b (initial)
export const COURSE_BEST_REQUEST = 'COURSE_BEST_REQUEST'
export const COURSE_BEST_SUCCESS = 'COURSE_BEST_SUCCESS'
export const COURSE_BEST_FAIL = 'COURSE_BEST_FAIL'

export const COURSE_REVIEW_REQUEST = 'COURSE_REVIEW_REQUEST'
export const COURSE_REVIEW_SUCCESS = 'COURSE_REVIEW_SUCCESS'
export const COURSE_REVIEW_FAIL = 'COURSE_REVIEW_FAIL'
export const COURSE_REVIEW_RESET = 'COURSE_REVIEW_RESET'
