export const INSTRUCTOR_COURSE_LIST_REQUEST = 'INSTRUCTOR_COURSE_LIST_REQUEST'
export const INSTRUCTOR_COURSE_LIST_SUCCESS = 'INSTRUCTOR_COURSE_LIST_SUCCESS'
export const INSTRUCTOR_COURSE_LIST_FAIL = 'INSTRUCTOR_COURSE_LIST_FAIL'
export const INSTRUCTOR_COURSE_LIST_RESET = 'INSTRUCTOR_COURSE_LIST_RESET'

export const INSTRUCTOR_COURSE_DETAILS_REQUEST =
  'INSTRUCTOR_COURSE_DETAILS_REQUEST'
export const INSTRUCTOR_COURSE_DETAILS_SUCCESS =
  'INSTRUCTOR_COURSE_DETAILS_SUCCESS'
export const INSTRUCTOR_COURSE_DETAILS_FAIL = 'INSTRUCTOR_COURSE_DETAILS_FAIL'
export const INSTRUCTOR_COURSE_DETAILS_RESET = 'INSTRUCTOR_COURSE_DETAILS_RESET'

export const INSTRUCTOR_COURSE_UPDATE_REQUEST =
  'INSTRUCTOR_COURSE_UPDATE_REQUEST'
export const INSTRUCTOR_COURSE_UPDATE_SUCCESS =
  'INSTRUCTOR_COURSE_UPDATE_SUCCESS'
export const INSTRUCTOR_COURSE_UPDATE_FAIL = 'INSTRUCTOR_COURSE_UPDATE_FAIL'
export const INSTRUCTOR_COURSE_UPDATE_RESET = 'INSTRUCTOR_COURSE_UPDATE_RESET'
