export const INSTRUCTOR_COURSE_LIST_REQUEST = 'INSTRUCTOR_COURSE_LIST_REQUEST'
export const INSTRUCTOR_COURSE_LIST_SUCCESS = 'INSTRUCTOR_COURSE_LIST_SUCCESS'
export const INSTRUCTOR_COURSE_LIST_FAIL = 'INSTRUCTOR_COURSE_LIST_FAIL'
export const INSTRUCTOR_COURSE_LIST_RESET = 'INSTRUCTOR_COURSE_LIST_RESET'

export const INSTRUCTOR_COURSE_DETAILS_REQUEST =
  'INSTRUCTOR_COURSE_DETAILS_REQUEST'
export const INSTRUCTOR_COURSE_DETAILS_SUCCESS =
  'INSTRUCTOR_COURSE_DETAILS_SUCCESS'
export const INSTRUCTOR_COURSE_DETAILS_FAIL = 'INSTRUCTOR_COURSE_DETAILS_FAIL'
export const INSTRUCTOR_COURSE_DETAILS_RESET = 'INSTRUCTOR_COURSE_DETAILS_RESET'

export const INSTRUCTOR_COURSE_UPDATE_REQUEST =
  'INSTRUCTOR_COURSE_UPDATE_REQUEST'
export const INSTRUCTOR_COURSE_UPDATE_SUCCESS =
  'INSTRUCTOR_COURSE_UPDATE_SUCCESS'
export const INSTRUCTOR_COURSE_UPDATE_FAIL = 'INSTRUCTOR_COURSE_UPDATE_FAIL'
export const INSTRUCTOR_COURSE_UPDATE_RESET = 'INSTRUCTOR_COURSE_UPDATE_RESET'

export const INSTRUCTOR_COURSE_CREATE_REQUEST =
  'INSTRUCTOR_COURSE_CREATE_REQUEST'
export const INSTRUCTOR_COURSE_CREATE_SUCCESS =
  'INSTRUCTOR_COURSE_CREATE_SUCCESS'
export const INSTRUCTOR_COURSE_CREATE_FAIL = 'INSTRUCTOR_COURSE_CREATE_FAIL'
export const INSTRUCTOR_COURSE_CREATE_RESET = 'INSTRUCTOR_COURSE_CREATE_RESET'

export const INSTRUCTOR_COURSE_DELETE_REQUEST =
  'INSTRUCTOR_COURSE_DELETE_REQUEST'
export const INSTRUCTOR_COURSE_DELETE_SUCCESS =
  'INSTRUCTOR_COURSE_DELETE_SUCCESS'
export const INSTRUCTOR_COURSE_DELETE_FAIL = 'INSTRUCTOR_COURSE_DELETE_FAIL'
export const INSTRUCTOR_COURSE_DELETE_RESET = 'INSTRUCTOR_COURSE_DELETE_RESET'

export const INSTRUCTOR_ADD_CONTENT_REQUEST = 'INSTRUCTOR_ADD_CONTENT_REQUEST'
export const INSTRUCTOR_ADD_CONTENT_SUCCESS = 'INSTRUCTOR_ADD_CONTENT_SUCCESS'
export const INSTRUCTOR_ADD_CONTENT_FAIL = 'INSTRUCTOR_ADD_CONTENT_FAIL'
export const INSTRUCTOR_ADD_CONTENT_RESET = 'INSTRUCTOR_ADD_CONTENT_RESET'
