export const USER_NOTIFICATION_REQUEST = 'USER_NOTIFICATION_REQUEST'
export const USER_NOTIFICATION_SUCCESS = 'USER_NOTIFICATION_SUCCESS'
export const USER_NOTIFICATION_FAIL = 'USER_NOTIFICATION_FAIL'
export const USER_NOTIFICATION_RESET = 'USER_NOTIFICATION_RESET'

export const NOTIFICATION_READ_REQUEST = 'NOTIFICATION_READ_REQUEST'
export const NOTIFICATION_READ_SUCCESS = 'NOTIFICATION_READ_SUCCESS'
export const NOTIFICATION_READ_FAIL = 'NOTIFICATION_READ_FAIL'
export const NOTIFICATION_READ_RESET = 'NOTIFICATION_READ_RESET'

export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST'
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS'
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL'
export const NOTIFICATION_DELETE_RESET = 'NOTIFICATION_DELETE_RESET'
