export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_ALL_REQUEST = 'ORDER_ALL_REQUEST'
export const ORDER_ALL_SUCCESS = 'ORDER_ALL_SUCCESS'
export const ORDER_ALL_FAIL = 'ORDER_ALL_FAIL'
