const products = [
  {
    _id: "1",
    name: "Introduction to Javascript",
    image: "/images/javascript.jpg",
    description: "Javascript is the most high demand in the industry nowaday.",
    instructor: "John Doe",
    category: "Programming",
    price: 49.99,
    rating: 5,
    numReviews: 4,
  },
  {
    _id: "2",
    name: "Introduction to C++",
    image: "/images/cplusplus.jpg",
    description: "C++ is the most high demand in the industry nowaday.",
    instructor: "John Doe",
    category: "Programming",
    price: 20.99,
    rating: 3,
    numReviews: 2,
  },
  {
    _id: "3",
    name: "Introduction to Typescript",
    image: "/images/typescript.jpg",
    description: "Typescript is the most high demand in the industry nowaday.",
    instructor: "John Doe",
    category: "Programming",
    price: 22.99,
    rating: 1,
    numReviews: 4,
  },
  {
    _id: "4",
    name: "Introduction to Python",
    image: "/images/python.jpg",
    description: "Python is the most high demand in the industry nowaday.",
    instructor: "John Doe",
    category: "Programming",
    price: 10.99,
    rating: 4.5,
    numReviews: 4,
  },
];

export default products;
